# Generated by Django 5.2.8 on 2025-12-01 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.CharField(blank=True, choices=[('Bridal', 'Bridal'), ('Groom', 'Groom'), ('Colors', 'Colors'), ('Decor', 'Decor'), ('Accessories', 'Accessories')], max_length=50),
        ),
        migrations.CreateModel(
            name='BoardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='board_images/')),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bridalapp.board')),
            ],
        ),
    ]
