# Generated by Django 5.2.8 on 2025-12-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridalapp', '0004_profile_facebook_profile_gender_profile_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(blank=True, choices=[('Bridal', 'Bridal'), ('Groom', 'Groom'), ('Colors', 'Colors'), ('Accessories', 'Accessories'), ('Decor', 'Decor')], max_length=50),
        ),
    ]
