# Generated by Django 5.2.8 on 2025-12-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridalapp', '0005_alter_board_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boarditem',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='boarditem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='boarditem',
            name='label',
        ),
        migrations.RemoveField(
            model_name='boarditem',
            name='note',
        ),
        migrations.AddField(
            model_name='board',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='board_covers/'),
        ),
        migrations.AddField(
            model_name='boarditem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boarditem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(blank=True, choices=[('Bridal', 'Bridal'), ('Groom', 'Groom'), ('Accessories', 'Accessories'), ('Decor', 'Decor')], max_length=50),
        ),
    ]
