# Generated by Django 5.2.8 on 2025-12-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridalapp', '0007_savedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedimage',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
