# Generated by Django 5.2.8 on 2025-12-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridalapp', '0008_alter_savedimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='blog-tips/')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='inspirations/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Photography', 'Photography'), ('Decor', 'Decor'), ('Invitations', 'Invitations'), ('Catering', 'Catering'), ('Makeup', 'Makeup'), ('Bridal Wear', 'Bridal Wear'), ('Groom Wear', 'Groom Wear'), ('Venue', 'Venue')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='vendors/')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
