# Generated by Django 5.2.8 on 2025-12-09 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridalapp', '0009_blogpost_inspiration_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('Wedding Planner', 'Wedding Planner'), ('Photographer', 'Photographer'), ('Makeup Artist', 'Makeup Artist'), ('Hair Stylist', 'Hair Stylist'), ('Cake Designer', 'Cake Designer'), ('Florist', 'Florist'), ('Decor Stylist', 'Decor Stylist'), ('Dress Designer', 'Dress Designer'), ('Suit Designer', 'Suit Designer'), ('Caterer', 'Caterer'), ('Venue', 'Venue'), ('Invitation Designer', 'Invitation Designer')], max_length=100),
        ),
    ]
