# Generated by Django 5.2.8 on 2025-12-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridalapp', '0010_vendor_location_alter_vendor_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='website',
            new_name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='email',
        ),
    ]
