# Generated by Django 5.2.8 on 2025-12-10 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridalapp', '0011_rename_website_vendor_whatsapp_remove_vendor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='boards/'),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='savedimage',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_images', to='bridalapp.board'),
        ),
        migrations.AlterField(
            model_name='savedimage',
            name='image',
            field=models.ImageField(upload_to='board_items/'),
        ),
    ]
