# Generated by Django 5.2.8 on 2025-12-10 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridalapp', '0012_alter_board_cover_image_alter_board_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='savedimage',
            name='image',
        ),
        migrations.AddField(
            model_name='savedimage',
            name='image_filename',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
