# Generated by Django 5.2.8 on 2025-12-10 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridalapp', '0013_remove_board_cover_image_remove_savedimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedimage',
            name='image_filename',
        ),
        migrations.AddField(
            model_name='board',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='boards/'),
        ),
        migrations.AddField(
            model_name='savedimage',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='board_items/'),
            preserve_default=False,
        ),
    ]
